"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import petstore
from petstore import Petstore


def test_user_sdk_create_user():
    s = Petstore(
        api_key="<YOUR_API_KEY_HERE>",
    )

    assert s is not None

    res = s.user.create_user(
        request={
            "id": 10,
            "username": "theUser",
            "first_name": "John",
            "last_name": "James",
            "email": "john@email.com",
            "password": "12345",
            "phone": "12345",
            "user_status": 1,
        }
    )
    assert res is not None
    assert res is not None
    assert res == petstore.User(
        id=10,
        username="theUser",
        first_name="John",
        last_name="James",
        email="john@email.com",
        password="12345",
        phone="12345",
        user_status=1,
    )


def test_user_sdk_create_users_with_list_input():
    s = Petstore(
        api_key="<YOUR_API_KEY_HERE>",
    )

    assert s is not None

    res = s.user.create_users_with_list_input(
        request=[
            {
                "id": 10,
                "username": "theUser",
                "first_name": "John",
                "last_name": "James",
                "email": "john@email.com",
                "password": "12345",
                "phone": "12345",
                "user_status": 1,
            },
        ]
    )
    assert res is not None
    assert res is not None
    assert res == petstore.User(
        id=10,
        username="theUser",
        first_name="John",
        last_name="James",
        email="john@email.com",
        password="12345",
        phone="12345",
        user_status=1,
    )


def test_user_sdk_login_user():
    s = Petstore(
        api_key="<YOUR_API_KEY_HERE>",
    )

    assert s is not None

    res = s.user.login_user()
    assert res is not None
    assert res is not None
    assert res == "<value>"


def test_user_sdk_logout_user():
    s = Petstore(
        api_key="<YOUR_API_KEY_HERE>",
    )

    assert s is not None

    s.user.logout_user()


def test_user_sdk_get_user_by_name():
    s = Petstore(
        api_key="<YOUR_API_KEY_HERE>",
    )

    assert s is not None

    res = s.user.get_user_by_name(username="Zachery_Lubowitz15")
    assert res is not None
    assert res is not None
    assert res == petstore.User(
        id=10,
        username="theUser",
        first_name="John",
        last_name="James",
        email="john@email.com",
        password="12345",
        phone="12345",
        user_status=1,
    )


def test_user_sdk_update_user():
    s = Petstore(
        api_key="<YOUR_API_KEY_HERE>",
    )

    assert s is not None

    s.user.update_user(
        username="Dandre_Hand41",
        user={
            "id": 10,
            "username": "theUser",
            "first_name": "John",
            "last_name": "James",
            "email": "john@email.com",
            "password": "12345",
            "phone": "12345",
            "user_status": 1,
        },
    )


def test_user_sdk_delete_user():
    s = Petstore(
        api_key="<YOUR_API_KEY_HERE>",
    )

    assert s is not None

    res = s.user.delete_user(username="Demetris_Schmitt")
    assert res is not None
    assert res is not None
    assert res == petstore.User(
        id=10,
        username="theUser",
        first_name="John",
        last_name="James",
        email="john@email.com",
        password="12345",
        phone="12345",
        user_status=1,
    )
