"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import os
import petstore
from petstore import Petstore
from tests.test_client import create_test_http_client


def test_user_sdk_create_user():
    with Petstore(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=create_test_http_client("createUser"),
        api_key="<YOUR_API_KEY_HERE>",
    ) as s:
        assert s is not None

        res = s.user.create_user(
            request={
                "id": 10,
                "username": "theUser",
                "first_name": "John",
                "last_name": "James",
                "email": "john@email.com",
                "password": "12345",
                "phone": "12345",
                "user_status": 1,
            }
        )
        assert res is not None
        assert res == petstore.User(
            id=10,
            username="theUser",
            first_name="John",
            last_name="James",
            email="john@email.com",
            password="12345",
            phone="12345",
            user_status=1,
        )


def test_user_sdk_create_users_with_list_input():
    with Petstore(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=create_test_http_client("createUsersWithListInput"),
        api_key="<YOUR_API_KEY_HERE>",
    ) as s:
        assert s is not None

        res = s.user.create_users_with_list_input(
            request=[
                {
                    "id": 10,
                    "username": "theUser",
                    "first_name": "John",
                    "last_name": "James",
                    "email": "john@email.com",
                    "password": "12345",
                    "phone": "12345",
                    "user_status": 1,
                },
            ]
        )
        assert res is not None
        assert res == petstore.User(
            id=10,
            username="theUser",
            first_name="John",
            last_name="James",
            email="john@email.com",
            password="12345",
            phone="12345",
            user_status=1,
        )


def test_user_sdk_login_user():
    with Petstore(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=create_test_http_client("loginUser"),
        api_key="<YOUR_API_KEY_HERE>",
    ) as s:
        assert s is not None

        res = s.user.login_user()
        assert res is not None
        assert res.result is not None
        assert res.result == "<value>"


def test_user_sdk_logout_user():
    with Petstore(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=create_test_http_client("logoutUser"),
        api_key="<YOUR_API_KEY_HERE>",
    ) as s:
        assert s is not None

        s.user.logout_user()


def test_user_sdk_get_user_by_name():
    with Petstore(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=create_test_http_client("getUserByName"),
        api_key="<YOUR_API_KEY_HERE>",
    ) as s:
        assert s is not None

        res = s.user.get_user_by_name(username="Zachery_Lubowitz15")
        assert res is not None
        assert res == petstore.User(
            id=10,
            username="theUser",
            first_name="John",
            last_name="James",
            email="john@email.com",
            password="12345",
            phone="12345",
            user_status=1,
        )


def test_user_sdk_update_user():
    with Petstore(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=create_test_http_client("updateUser"),
        api_key="<YOUR_API_KEY_HERE>",
    ) as s:
        assert s is not None

        s.user.update_user(
            username="Dandre_Hand41",
            user={
                "id": 10,
                "username": "theUser",
                "first_name": "John",
                "last_name": "James",
                "email": "john@email.com",
                "password": "12345",
                "phone": "12345",
                "user_status": 1,
            },
        )


def test_user_sdk_delete_user():
    with Petstore(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=create_test_http_client("deleteUser"),
        api_key="<YOUR_API_KEY_HERE>",
    ) as s:
        assert s is not None

        res = s.user.delete_user(username="Demetris_Schmitt")
        assert res is not None
        assert res == petstore.User(
            id=10,
            username="theUser",
            first_name="John",
            last_name="James",
            email="john@email.com",
            password="12345",
            phone="12345",
            user_status=1,
        )
