"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import petstore
from petstore import Petstore


def test_store_get_inventory():
    s = Petstore(
        api_key="<YOUR_API_KEY_HERE>",
    )

    assert s is not None

    res = s.store.get_inventory()
    assert res is not None
    assert res is not None
    assert res == {
        "key": 373538,
    }


def test_store_place_order():
    s = Petstore(
        api_key="<YOUR_API_KEY_HERE>",
    )

    assert s is not None

    res = s.store.place_order(
        request={
            "id": 10,
            "pet_id": 198772,
            "quantity": 7,
            "status": petstore.OrderStatus.APPROVED,
        }
    )
    assert res is not None
    assert res is not None
    assert res == petstore.Order(
        id=10,
        pet_id=198772,
        quantity=7,
        status=petstore.OrderStatus.APPROVED,
    )


def test_store_get_order_by_id():
    s = Petstore(
        api_key="<YOUR_API_KEY_HERE>",
    )

    assert s is not None

    res = s.store.get_order_by_id(order_id=614993)
    assert res is not None
    assert res is not None
    assert res == petstore.Order(
        id=10,
        pet_id=198772,
        quantity=7,
        status=petstore.OrderStatus.APPROVED,
    )


def test_store_delete_order():
    s = Petstore(
        api_key="<YOUR_API_KEY_HERE>",
    )

    assert s is not None

    res = s.store.delete_order(order_id=127902)
    assert res is not None
    assert res is not None
    assert res == petstore.Order(
        id=10,
        pet_id=198772,
        quantity=7,
        status=petstore.OrderStatus.APPROVED,
    )
