"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .petstoreerror import PetstoreError
from typing import TYPE_CHECKING
from importlib import import_module
import builtins
import sys

if TYPE_CHECKING:
    from .apierrorinvalidinput import APIErrorInvalidInput, APIErrorInvalidInputData
    from .apierrornotfound import APIErrorNotFound, APIErrorNotFoundData
    from .apierrorunauthorized import APIErrorUnauthorized, APIErrorUnauthorizedData
    from .apiresponse import APIResponse, APIResponseTypedDict
    from .category import Category, CategoryTypedDict
    from .deleteorderop import DeleteOrderRequest, DeleteOrderRequestTypedDict
    from .deletepetop import DeletePetRequest, DeletePetRequestTypedDict
    from .deleteuserop import DeleteUserRequest, DeleteUserRequestTypedDict
    from .findpetsbystatusop import (
        FindPetsByStatusRequest,
        FindPetsByStatusRequestTypedDict,
        QueryParamStatus,
    )
    from .findpetsbytagsop import FindPetsByTagsRequest, FindPetsByTagsRequestTypedDict
    from .getorderbyidop import GetOrderByIDRequest, GetOrderByIDRequestTypedDict
    from .getpetbyidop import GetPetByIDRequest, GetPetByIDRequestTypedDict
    from .getuserbynameop import GetUserByNameRequest, GetUserByNameRequestTypedDict
    from .loginuserop import (
        LoginUserRequest,
        LoginUserRequestTypedDict,
        LoginUserResponse,
        LoginUserResponseTypedDict,
    )
    from .no_response_error import NoResponseError
    from .order import Order, OrderStatus, OrderTypedDict
    from .pet import Pet, PetTypedDict, Status
    from .responsevalidationerror import ResponseValidationError
    from .sdkerror import SDKError
    from .security import Security, SecurityTypedDict
    from .tag import Tag, TagTypedDict
    from .updateuserop import UpdateUserRequest, UpdateUserRequestTypedDict
    from .uploadfileop import UploadFileRequest, UploadFileRequestTypedDict
    from .user import User, UserTypedDict

__all__ = [
    "APIErrorInvalidInput",
    "APIErrorInvalidInputData",
    "APIErrorNotFound",
    "APIErrorNotFoundData",
    "APIErrorUnauthorized",
    "APIErrorUnauthorizedData",
    "APIResponse",
    "APIResponseTypedDict",
    "Category",
    "CategoryTypedDict",
    "DeleteOrderRequest",
    "DeleteOrderRequestTypedDict",
    "DeletePetRequest",
    "DeletePetRequestTypedDict",
    "DeleteUserRequest",
    "DeleteUserRequestTypedDict",
    "FindPetsByStatusRequest",
    "FindPetsByStatusRequestTypedDict",
    "FindPetsByTagsRequest",
    "FindPetsByTagsRequestTypedDict",
    "GetOrderByIDRequest",
    "GetOrderByIDRequestTypedDict",
    "GetPetByIDRequest",
    "GetPetByIDRequestTypedDict",
    "GetUserByNameRequest",
    "GetUserByNameRequestTypedDict",
    "LoginUserRequest",
    "LoginUserRequestTypedDict",
    "LoginUserResponse",
    "LoginUserResponseTypedDict",
    "NoResponseError",
    "Order",
    "OrderStatus",
    "OrderTypedDict",
    "Pet",
    "PetTypedDict",
    "PetstoreError",
    "QueryParamStatus",
    "ResponseValidationError",
    "SDKError",
    "Security",
    "SecurityTypedDict",
    "Status",
    "Tag",
    "TagTypedDict",
    "UpdateUserRequest",
    "UpdateUserRequestTypedDict",
    "UploadFileRequest",
    "UploadFileRequestTypedDict",
    "User",
    "UserTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "APIErrorInvalidInput": ".apierrorinvalidinput",
    "APIErrorInvalidInputData": ".apierrorinvalidinput",
    "APIErrorNotFound": ".apierrornotfound",
    "APIErrorNotFoundData": ".apierrornotfound",
    "APIErrorUnauthorized": ".apierrorunauthorized",
    "APIErrorUnauthorizedData": ".apierrorunauthorized",
    "APIResponse": ".apiresponse",
    "APIResponseTypedDict": ".apiresponse",
    "Category": ".category",
    "CategoryTypedDict": ".category",
    "DeleteOrderRequest": ".deleteorderop",
    "DeleteOrderRequestTypedDict": ".deleteorderop",
    "DeletePetRequest": ".deletepetop",
    "DeletePetRequestTypedDict": ".deletepetop",
    "DeleteUserRequest": ".deleteuserop",
    "DeleteUserRequestTypedDict": ".deleteuserop",
    "FindPetsByStatusRequest": ".findpetsbystatusop",
    "FindPetsByStatusRequestTypedDict": ".findpetsbystatusop",
    "QueryParamStatus": ".findpetsbystatusop",
    "FindPetsByTagsRequest": ".findpetsbytagsop",
    "FindPetsByTagsRequestTypedDict": ".findpetsbytagsop",
    "GetOrderByIDRequest": ".getorderbyidop",
    "GetOrderByIDRequestTypedDict": ".getorderbyidop",
    "GetPetByIDRequest": ".getpetbyidop",
    "GetPetByIDRequestTypedDict": ".getpetbyidop",
    "GetUserByNameRequest": ".getuserbynameop",
    "GetUserByNameRequestTypedDict": ".getuserbynameop",
    "LoginUserRequest": ".loginuserop",
    "LoginUserRequestTypedDict": ".loginuserop",
    "LoginUserResponse": ".loginuserop",
    "LoginUserResponseTypedDict": ".loginuserop",
    "NoResponseError": ".no_response_error",
    "Order": ".order",
    "OrderStatus": ".order",
    "OrderTypedDict": ".order",
    "Pet": ".pet",
    "PetTypedDict": ".pet",
    "Status": ".pet",
    "ResponseValidationError": ".responsevalidationerror",
    "SDKError": ".sdkerror",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "Tag": ".tag",
    "TagTypedDict": ".tag",
    "UpdateUserRequest": ".updateuserop",
    "UpdateUserRequestTypedDict": ".updateuserop",
    "UploadFileRequest": ".uploadfileop",
    "UploadFileRequestTypedDict": ".uploadfileop",
    "User": ".user",
    "UserTypedDict": ".user",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
