"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .petstoreerror import PetstoreError
from typing import Any, TYPE_CHECKING

from petstore.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .apierrorinvalidinput import APIErrorInvalidInput, APIErrorInvalidInputData
    from .apierrornotfound import APIErrorNotFound, APIErrorNotFoundData
    from .apierrorunauthorized import APIErrorUnauthorized, APIErrorUnauthorizedData
    from .apiresponse import APIResponse, APIResponseTypedDict
    from .category import Category, CategoryTypedDict
    from .deleteorderop import DeleteOrderRequest, DeleteOrderRequestTypedDict
    from .deletepetop import DeletePetRequest, DeletePetRequestTypedDict
    from .deleteuserop import DeleteUserRequest, DeleteUserRequestTypedDict
    from .findpetsbystatusop import (
        FindPetsByStatusRequest,
        FindPetsByStatusRequestTypedDict,
        QueryParamStatus,
    )
    from .findpetsbytagsop import FindPetsByTagsRequest, FindPetsByTagsRequestTypedDict
    from .getorderbyidop import GetOrderByIDRequest, GetOrderByIDRequestTypedDict
    from .getpetbyidop import GetPetByIDRequest, GetPetByIDRequestTypedDict
    from .getuserbynameop import GetUserByNameRequest, GetUserByNameRequestTypedDict
    from .loginuserop import (
        LoginUserRequest,
        LoginUserRequestTypedDict,
        LoginUserResponse,
        LoginUserResponseTypedDict,
    )
    from .no_response_error import NoResponseError
    from .order import Order, OrderStatus, OrderTypedDict
    from .pet import Pet, PetTypedDict, Status
    from .responsevalidationerror import ResponseValidationError
    from .sdkerror import SDKError
    from .security import Security, SecurityTypedDict
    from .tag import Tag, TagTypedDict
    from .updateuserop import UpdateUserRequest, UpdateUserRequestTypedDict
    from .uploadfileop import UploadFileRequest, UploadFileRequestTypedDict
    from .user import User, UserTypedDict

__all__ = [
    "APIErrorInvalidInput",
    "APIErrorInvalidInputData",
    "APIErrorNotFound",
    "APIErrorNotFoundData",
    "APIErrorUnauthorized",
    "APIErrorUnauthorizedData",
    "APIResponse",
    "APIResponseTypedDict",
    "Category",
    "CategoryTypedDict",
    "DeleteOrderRequest",
    "DeleteOrderRequestTypedDict",
    "DeletePetRequest",
    "DeletePetRequestTypedDict",
    "DeleteUserRequest",
    "DeleteUserRequestTypedDict",
    "FindPetsByStatusRequest",
    "FindPetsByStatusRequestTypedDict",
    "FindPetsByTagsRequest",
    "FindPetsByTagsRequestTypedDict",
    "GetOrderByIDRequest",
    "GetOrderByIDRequestTypedDict",
    "GetPetByIDRequest",
    "GetPetByIDRequestTypedDict",
    "GetUserByNameRequest",
    "GetUserByNameRequestTypedDict",
    "LoginUserRequest",
    "LoginUserRequestTypedDict",
    "LoginUserResponse",
    "LoginUserResponseTypedDict",
    "NoResponseError",
    "Order",
    "OrderStatus",
    "OrderTypedDict",
    "Pet",
    "PetTypedDict",
    "PetstoreError",
    "QueryParamStatus",
    "ResponseValidationError",
    "SDKError",
    "Security",
    "SecurityTypedDict",
    "Status",
    "Tag",
    "TagTypedDict",
    "UpdateUserRequest",
    "UpdateUserRequestTypedDict",
    "UploadFileRequest",
    "UploadFileRequestTypedDict",
    "User",
    "UserTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "APIErrorInvalidInput": ".apierrorinvalidinput",
    "APIErrorInvalidInputData": ".apierrorinvalidinput",
    "APIErrorNotFound": ".apierrornotfound",
    "APIErrorNotFoundData": ".apierrornotfound",
    "APIErrorUnauthorized": ".apierrorunauthorized",
    "APIErrorUnauthorizedData": ".apierrorunauthorized",
    "APIResponse": ".apiresponse",
    "APIResponseTypedDict": ".apiresponse",
    "Category": ".category",
    "CategoryTypedDict": ".category",
    "DeleteOrderRequest": ".deleteorderop",
    "DeleteOrderRequestTypedDict": ".deleteorderop",
    "DeletePetRequest": ".deletepetop",
    "DeletePetRequestTypedDict": ".deletepetop",
    "DeleteUserRequest": ".deleteuserop",
    "DeleteUserRequestTypedDict": ".deleteuserop",
    "FindPetsByStatusRequest": ".findpetsbystatusop",
    "FindPetsByStatusRequestTypedDict": ".findpetsbystatusop",
    "QueryParamStatus": ".findpetsbystatusop",
    "FindPetsByTagsRequest": ".findpetsbytagsop",
    "FindPetsByTagsRequestTypedDict": ".findpetsbytagsop",
    "GetOrderByIDRequest": ".getorderbyidop",
    "GetOrderByIDRequestTypedDict": ".getorderbyidop",
    "GetPetByIDRequest": ".getpetbyidop",
    "GetPetByIDRequestTypedDict": ".getpetbyidop",
    "GetUserByNameRequest": ".getuserbynameop",
    "GetUserByNameRequestTypedDict": ".getuserbynameop",
    "LoginUserRequest": ".loginuserop",
    "LoginUserRequestTypedDict": ".loginuserop",
    "LoginUserResponse": ".loginuserop",
    "LoginUserResponseTypedDict": ".loginuserop",
    "NoResponseError": ".no_response_error",
    "Order": ".order",
    "OrderStatus": ".order",
    "OrderTypedDict": ".order",
    "Pet": ".pet",
    "PetTypedDict": ".pet",
    "Status": ".pet",
    "ResponseValidationError": ".responsevalidationerror",
    "SDKError": ".sdkerror",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "Tag": ".tag",
    "TagTypedDict": ".tag",
    "UpdateUserRequest": ".updateuserop",
    "UpdateUserRequestTypedDict": ".updateuserop",
    "UploadFileRequest": ".uploadfileop",
    "UploadFileRequestTypedDict": ".uploadfileop",
    "User": ".user",
    "UserTypedDict": ".user",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
