"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from petstore.models import PetstoreError
from petstore.types import BaseModel
from typing import Optional


class APIErrorUnauthorizedData(BaseModel):
    status: int
    error: str


@dataclass(unsafe_hash=True)
class APIErrorUnauthorized(PetstoreError):
    r"""Unauthorized error"""

    data: APIErrorUnauthorizedData = field(hash=False)

    def __init__(
        self,
        data: APIErrorUnauthorizedData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
