"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from petstore.types import BaseModel, UNSET_SENTINEL
from petstore.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class QueryParamStatus(str, Enum):
    r"""Status values that need to be considered for filter"""

    AVAILABLE = "available"
    PENDING = "pending"
    SOLD = "sold"


class FindPetsByStatusRequestTypedDict(TypedDict):
    status: NotRequired[QueryParamStatus]
    r"""Status values that need to be considered for filter"""


class FindPetsByStatusRequest(BaseModel):
    status: Annotated[
        Optional[QueryParamStatus],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = QueryParamStatus.AVAILABLE
    r"""Status values that need to be considered for filter"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
