"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from petstore.types import BaseModel, UNSET_SENTINEL
from petstore.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class LoginUserRequestTypedDict(TypedDict):
    username: NotRequired[str]
    r"""The user name for login"""
    password: NotRequired[str]
    r"""The password for login in clear text"""


class LoginUserRequest(BaseModel):
    username: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The user name for login"""

    password: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The password for login in clear text"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["username", "password"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class LoginUserResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: str


class LoginUserResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: str
