"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from petstore.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OrderStatus(str, Enum):
    r"""Order Status"""

    PLACED = "placed"
    APPROVED = "approved"
    DELIVERED = "delivered"


class OrderTypedDict(TypedDict):
    id: NotRequired[int]
    pet_id: NotRequired[int]
    quantity: NotRequired[int]
    ship_date: NotRequired[datetime]
    status: NotRequired[OrderStatus]
    r"""Order Status"""
    complete: NotRequired[bool]


class Order(BaseModel):
    id: Optional[int] = None

    pet_id: Annotated[Optional[int], pydantic.Field(alias="petId")] = None

    quantity: Optional[int] = None

    ship_date: Annotated[Optional[datetime], pydantic.Field(alias="shipDate")] = None

    status: Optional[OrderStatus] = None
    r"""Order Status"""

    complete: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["id", "petId", "quantity", "shipDate", "status", "complete"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Order.model_rebuild()
except NameError:
    pass
