"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .category import Category, CategoryTypedDict
from .tag import Tag, TagTypedDict
from enum import Enum
from petstore.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Status(str, Enum):
    r"""pet status in the store"""

    AVAILABLE = "available"
    PENDING = "pending"
    SOLD = "sold"


class PetTypedDict(TypedDict):
    name: str
    photo_urls: List[str]
    id: NotRequired[int]
    category: NotRequired[CategoryTypedDict]
    tags: NotRequired[List[TagTypedDict]]
    status: NotRequired[Status]
    r"""pet status in the store"""


class Pet(BaseModel):
    name: str

    photo_urls: Annotated[List[str], pydantic.Field(alias="photoUrls")]

    id: Optional[int] = None

    category: Optional[Category] = None

    tags: Optional[List[Tag]] = None

    status: Optional[Status] = None
    r"""pet status in the store"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "category", "tags", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Pet.model_rebuild()
except NameError:
    pass
