"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .user import User, UserTypedDict
from petstore.types import BaseModel, UNSET_SENTINEL
from petstore.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateUserRequestTypedDict(TypedDict):
    username: str
    r"""name that needs to be updated"""
    user: NotRequired[UserTypedDict]
    r"""Update an existent user in the store"""


class UpdateUserRequest(BaseModel):
    username: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""name that needs to be updated"""

    user: Annotated[
        Optional[User],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
    r"""Update an existent user in the store"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["User"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
