"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import io
from petstore.types import BaseModel, UNSET_SENTINEL
from petstore.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import IO, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class UploadFileRequestTypedDict(TypedDict):
    pet_id: int
    r"""ID of pet to update"""
    additional_metadata: NotRequired[str]
    r"""Additional Metadata"""
    request_body: NotRequired[Union[bytes, IO[bytes], io.BufferedReader]]


class UploadFileRequest(BaseModel):
    pet_id: Annotated[
        int,
        pydantic.Field(alias="petId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""ID of pet to update"""

    additional_metadata: Annotated[
        Optional[str],
        pydantic.Field(alias="additionalMetadata"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Additional Metadata"""

    request_body: Annotated[
        Optional[Union[bytes, IO[bytes], io.BufferedReader]],
        FieldMetadata(request=True),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["additionalMetadata", "RequestBody"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
