"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from petstore.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UserTypedDict(TypedDict):
    id: NotRequired[int]
    username: NotRequired[str]
    first_name: NotRequired[str]
    last_name: NotRequired[str]
    email: NotRequired[str]
    password: NotRequired[str]
    phone: NotRequired[str]
    user_status: NotRequired[int]
    r"""User Status"""


class User(BaseModel):
    id: Optional[int] = None

    username: Optional[str] = None

    first_name: Annotated[Optional[str], pydantic.Field(alias="firstName")] = None

    last_name: Annotated[Optional[str], pydantic.Field(alias="lastName")] = None

    email: Optional[str] = None

    password: Optional[str] = None

    phone: Optional[str] = None

    user_status: Annotated[Optional[int], pydantic.Field(alias="userStatus")] = None
    r"""User Status"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "username",
                "firstName",
                "lastName",
                "email",
                "password",
                "phone",
                "userStatus",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    User.model_rebuild()
except NameError:
    pass
