name: Speakeasy Testing
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target:
        required: true
        default: all
        type: string
permissions:
  contents: read
jobs:
  Python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - run: pipx install "poetry~=1.8"
      - run: poetry install
      - run: curl -fsSL https://go.speakeasy.com/cli-install.sh | sh
      - run: speakeasy test
        env:
          SPEAKEASY_API_KEY: ${{ secrets.SPEAKEASY_API_KEY }}
